// This file is auto-generated by Next.js. Do not edit this file directly.
// It will be overwritten by Next.js during development/build.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
